# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build beekeeb Toucan'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["toucan_left rgbled_adapter nice_view_gem","toucan_right rgbled_adapter"]'
      alphas: '["QWERTY"]'
      branches: '["zmkfirmware/zmk/v0.3.0"]'
      kconfig: |-
        ["CONFIG_ZMK_POINTING=y
        CONFIG_ZMK_BATTERY_REPORTING=y
        CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
        CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
        CONFIG_BT_CTLR_TX_PWR_PLUS_8=y"]
